pipeline:

  staging-build:
    image: plugins/docker
    repo: <DOCKER_USERNAME>/${DRONE_REPO_NAME}
    tags:
      - ${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
    secrets: [ docker_username, docker_password ]
    when:
      event: [ push ]
      branch:
        exclude: [ master ]

  staging-hubconfig:
    image: coinlion/kms-vault
    pull: true
    environment:
      - HUB_CONFIG=/config/hub
      - S3_HUB_CONFIG_BUCKET=<S3_HUB_CONFIG_BUCKET>
      - AWS_DEFAULT_REGION=us-east-1
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    when:
      event: [ push ]
      branch:
        exclude: [ master ]
    volumes:
      - /config:/config

  staging-kubectl:
    image: coinlion/kops
    commands:
      - kops export kubecfg dev.coinlion.io
      - kubectl cluster-info
    environment:
      - KUBECONFIG=/kube/config
      - AWS_REGION=us-east-1
      - KOPS_STATE_STORE=s3://<S3_KOPS_STATE_STORE>
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    when:
      event: [ push ]
      branch:
        exclude: [ master ]
    volumes:
      - /kube:/kube

  staging-infra:
    image: coinlion/infra-staging
    pull: true
    environment:
      - HUB_CONFIG=/config/hub
      - KUBECONFIG=/kube/config
      - GITHUB_ACTIVE_ACCOUNT=<GITHUB_ACCOUNT>
      - AWS_ECR_HOST=<AWS_ECR_HOST>
    when:
      event: [ push ]
      branch:
        exclude: [ master ]
    volumes:
      - /config:/config
      - /kube:/kube

# QA pipeline
  qa-build:
    image: plugins/docker
    repo: <DOCKER_USERNAME>/${DRONE_REPO_NAME}
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_TAG}
    when:
      event: [ tag ]

  qa-hubconfig:
    image: coinlion/kms-vault
    pull: true
    environment:
      - HUB_CONFIG=/config/hub
      - S3_HUB_CONFIG_BUCKET=<S3_HUB_CONFIG_BUCKET>
      - AWS_DEFAULT_REGION=us-east-1
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    when:
      event: [ tag ]
    volumes:
      - /config:/config

  qa-kubectl:
    image: coinlion/kops
    commands:
      - kops export kubecfg qa.coinlion.io
      - kubectl cluster-info
    environment:
      - KUBECONFIG=/kube/config
      - AWS_REGION=us-east-1
      - KOPS_STATE_STORE=s3://<S3_KOPS_STATE_STORE>
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    when:
      event: [ tag ]
    volumes:
      - /kube:/kube

  qa-infra:
    image: coinlion/infra-qa
    pull: true
    environment:
      - HUB_CONFIG=/config/hub
      - KUBECONFIG=/kube/config
      - GITHUB_ACTIVE_ACCOUNT=<GITHUB_ACCOUNT>
      - AWS_ECR_HOST=<AWS_ECR_HOST>
    when:
      event: [ tag ]
    volumes:
      - /config:/config
      - /kube:/kube